### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nrolland**

### CODE REVIEW

**Comment by gasche** [comment]
Hi Nicolas,

Thanks a lot for these 14 PRs, it looks like you did very useful work. Unfortunately, the fact that there are so many separate PRs makes it a lot more work for me to integrate, in particular because they all conflict with each other (your editor apparently decided to change the umlaut in Daniel Hillerström's name in each of them).

Would it be possible for you to send a single PR with all your changes, or at least a smaller number of PRs that do not conflict with each other?

Finally, a minor remark: I would like to preserve a clear separation between presentations that correspond to accepted papers (this repository is, first of all, a place to find the preprints) and the invited talks. I don't like the idea of adding keynotes in the middle of ICFP papers, undifferentiated. Could you maybe add two subcategories to the "ICFP" section, "Keynotes" and "Presented papers", to clearly distinguish them?

**Comment by nrolland** [comment]
I used Github web interface... can't you just merge the first selecting Github umlaut ? the other one should not conflict then

**Comment by nrolland** [comment]
feel free to reject what is not just additional info to entries. it would be useful though to have an index for the videos though, as it currently does not exist

**Comment by gasche** [comment]
So the magic was along the lines of:

```
for f in $(seq 30 43); do
  wget https://github.com/gasche/icfp2017-papers/pull/$i.patch
  git apply --reject $i.patch
done
```

The `--reject` option merges the parts of the patch that do not conflict (and creates a `.rej` file for the rest that can be just ignored).

**Comment by nrolland** [comment]
Instead of 14 clicks ?

**Comment by gasche** [comment]
Again, I believe that 14 clicks would not have worked, because the various diffs conflict with each other.

**Comment by nrolland** [comment]
well it's the same change, so there are no real conflict..

**Comment by gasche** [comment]
Okay, so two points:

1. You are right, I just tried in a test repo, and Github apparently knows how to automatically solve these spurious conflicts without going into conflict-resolution mode (while `git am` for example does not, for those patches). I am more familiar with the `git` command-line than with github's logic, so I assumed it would (not) work as in the command-line. I could have done it with 14*4 clicks instead of a script (one to select the PR, two to merge, one to go back to the PR list).

2. I do not appreciate the way you are responding to this issue. The reason why I did this is because you sent 14 conflicting pull-requests, instead of a single pull request with all your changes (which would have been easy for you given that you wrote all of them at the exact same time). I appreciate your contribution and did not criticize the choice you made in how to send your PRs -- I asked for a single PR which you didn't do, and then I solved the problem in my own way and posted my solution for future reference. Appropriate reactions from you would be "thanks !", saying nothing, or maybe "I checked that github can solve these conflicts, but I guess the script works just as well", not trying to have the last word because I remark that you are giving me more work than necessary.

I'm giving this feedback because I hope that I or other maintainers of similar repositories will receive further useful contributions from you, and I think being explicit about how I perceive our interaction now may be helpful in the future.

Cheers

**Comment by nrolland** [comment]
I checked as well and there are, as expected, no problem to begin with.
 
I understand you have spent time to come up with a script to solve this problem that you perceived as real, but you might want to consider that this repo is really just for a simple text file. 

There are no real reason to get into hair splitting mode over the best way to edit a text file, or at least that I would be interested in.

In the end :  You have the info, you do what you want with it.  You can even ignore it, watch those 14 videos, write down the time. I don't think that will be faster than clicking 14*4 times.

Good luck to you

**Pull request closed without merging**
